# Module: NumPy Assignments
## Lesson: NumPy






### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.



In [1]:
import numpy as np
arr = np.random.randint(1,21,size=(5,5))
print(arr)
arr[:,2] = 1 
print(arr)

arr2 = np.arange(1,17).reshape(4,4)
print(arr2)
np.fill_diagonal(arr2,0)
print(arr2)

[[ 3  9  6 12  7]
 [ 9 17 18 10  4]
 [20 17 13 17 15]
 [14  8 12 13 14]
 [16 15 10  5  5]]
[[ 3  9  1 12  7]
 [ 9 17  1 10  4]
 [20 17  1 17 15]
 [14  8  1 13 14]
 [16 15  1  5  5]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.



In [2]:
arr = np.arange(1,37).reshape(6,6)
print(arr)
subarr = arr[2:5,1:4]
print(subarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



In [3]:
arr1 = np.random.randint(1,11, size = (3,4))
arr2 = np.random.randint(1,11, size = (3,4))
print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 * arr2)


[[ 6  3  2  8]
 [ 6  2  5  6]
 [10  9  6  4]]
[[10  4  6  7]
 [ 8  3  6  8]
 [ 4  3 10  4]]
[[16  7  8 15]
 [14  5 11 14]
 [14 12 16  8]]
[[60 12 12 56]
 [48  6 30 48]
 [40 27 60 16]]


In [4]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
rowsum = arr.sum(axis=1)
print(rowsum)
colSum = arr.sum(axis=0)
print(colSum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [5]:
arr = np.random.randint(1,11,size = (5,5))
print(arr)
mean = np.mean(arr)
median = np.median(arr)
sd = np.std(arr)
var = np.var(arr)
print(mean,median,sd,var)

arr2 = np.arange(1,10).reshape(3,3)
print(arr2)
mean2 = np.mean(arr2)
std2 = np.std(arr2) 
normalizedArr = (arr2 - mean2) / std2
print(normalizedArr)

[[ 3  2  8  4  3]
 [ 3  3  7  3  6]
 [ 1  7  1  4 10]
 [ 6  3  5  8  4]
 [10  3  6  5  5]]
4.8 4.0 2.449489742783178 5.999999999999999
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.



In [6]:
arr = np.random.randint(1,11,size=(3,3))
print(arr)
arr1 = np.random.randint(1,11,size=(3,))
print(arr1)
result = arr + arr1
print(result)

arr = np.random.randint(1,11,size=(4,4))
print(arr)
arr1 = np.random.randint(1,11,size = (4,))
print(arr1)
result = arr - arr1[:,np.newaxis]
print(result)


[[10  3  5]
 [ 1  3  4]
 [ 8  2  1]]
[5 7 5]
[[15 10 10]
 [ 6 10  9]
 [13  9  6]]
[[3 7 3 2]
 [8 3 3 4]
 [3 9 1 7]
 [5 8 9 6]]
[1 6 9 4]
[[ 2  6  2  1]
 [ 2 -3 -3 -2]
 [-6  0 -8 -2]
 [ 1  4  5  2]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.



In [7]:
arr = np.random.randint(1,11,size=(3,3))
print(arr)
print(np.linalg.det(arr))
print(np.linalg.inv(arr))
print(np.linalg.eigvals(arr))

arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))
result = np.dot(arr1,arr2)
print(result)

[[ 3  6  9]
 [10  5  6]
 [ 5 10  6]]
404.99999999999983
[[-7.40740741e-02  1.33333333e-01 -2.22222222e-02]
 [-7.40740741e-02 -6.66666667e-02  1.77777778e-01]
 [ 1.85185185e-01 -1.02798428e-17 -1.11111111e-01]]
[20.08305229+0.j         -3.04152615+3.30384261j -3.04152615-3.30384261j]
[[ 40  89]
 [ 67 106]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



In [13]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr = arr.reshape(1,9)
print(arr)
arr = arr.reshape(9,1)
print(arr)

arr2 = np.random.randint(1,21,size=(5,5))
print(arr2)
flattenedarr= arr2.flatten()
print(flattenedarr)
reshapedarr = flattenedarr.reshape(5,5)
print(reshapedarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 5 15 18  8  9]
 [ 7 10 19 17 19]
 [ 2  9  7  8 11]
 [14 11  2 19 15]
 [11 15 15  6 20]]
[ 5 15 18  8  9  7 10 19 17 19  2  9  7  8 11 14 11  2 19 15 11 15 15  6
 20]
[[ 5 15 18  8  9]
 [ 7 10 19 17 19]
 [ 2  9  7  8 11]
 [14 11  2 19 15]
 [11 15 15  6 20]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [23]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)
arr1 = np.random.randint(1,21,size=(4,4))
print(arr1)
arr1[arr1>10] = 10
print(arr1)

[[ 6  8 15 19  3]
 [17  3  3 13  8]
 [ 2 11 15 13  5]
 [12  7  6 18 10]
 [ 6 19 12 18 15]]
[ 6  3  6 15]
[[14  9 15  2]
 [ 2  7  2  9]
 [ 8 19  7 13]
 [ 9 11  7 11]]
[[10  9 10  2]
 [ 2  7  2  9]
 [ 8 10  7 10]
 [ 9 10  7 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



In [28]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('ahmed',25,62.5),
    ('mahmoud',27,75.6),
    ('mohamed',21,78.3)
],dtype=data_type)
print(data)
sorted_data = np.sort(data,order='age')
print(sorted_data)

[('ahmed', 25, 62.5) ('mahmoud', 27, 75.6) ('mohamed', 21, 78.3)]
[('mohamed', 21, 78.3) ('ahmed', 25, 62.5) ('mahmoud', 27, 75.6)]


In [29]:
data_type = [('x','i4'),('y','i4')]
data = np.array(
    [(2,4),(3,5)],dtype=data_type
)
print(data)

[(2, 4) (3, 5)]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [30]:
import numpy.ma as ma
arr = np.random.randint(1,15,size=(4,4))
print(arr)
masked = ma.masked_greater(arr,10)
print(masked)
summ = masked.sum()
print(summ)

[[ 1 11 11  9]
 [ 8  9 11 14]
 [ 8  4  5  1]
 [ 1 13  3 11]]
[[1 -- -- 9]
 [8 9 -- --]
 [8 4 5 1]
 [1 -- 3 --]]
49


In [31]:
arr = np.random.randint(1,15,size=(3,3))
