In [ ]:
import numpy as np
## create 1D array 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3])
arr2.reshape(1,3)

array([[1, 2, 3]])

In [7]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.arange(0,11,2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [21]:
print(arr3.dtype)
print(arr3.size)
print(arr3.itemsize)
print(arr3.ndim)

int64
6
8
2


In [23]:
arr11 = np.array([1,2,3,4,5])
arr22 = np.array([10,20,30,40,50])
print(arr11 + arr22)

[11 22 33 44 55]


In [27]:
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [35]:
## slicing and indexing
arr6= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr6[0][0])
print(arr6[1:,2:])
print(arr6[0: , 0:2])


1
[[ 7  8]
 [11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [44]:
print(arr6[0,0])
arr6[0,0] = 100
print(arr6)


1
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [46]:
## Normalization
data = np.array([1,2,3,4,5])

## mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize data
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
data2 = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data2)
print(f"mean: {mean}")

median = np.median(data2)
print(f"median: {median}")

std = np.std(data2)
print(f"standard deviation: {std}")

variance = np.var(data2)
print(f"variance: {variance}")

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [54]:
## logical operation
data2[(data2 > 5) & (data2 < 9)]

array([6, 7, 8])