In [2]:
import numpy as np
numbers = np.array([1,2,3,4,5])
result = numbers * 2
print(result)

[ 2  4  6  8 10]


In [3]:
## list vs numpy array
lst = [1,2,3,4]
numarr = np.array([1,2,3,4])
print(lst * 2)
print(numarr * 2)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [7]:
## ndim , shape, size , dtype
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize) ## int64 uses 64 bits so 64 / 8 = 8
print(arr.nbytes) ## 8 * 6


2
(2, 3)
6
int64
8
48


In [11]:
arr2 = np.zeros(5)
print(arr2)
print(arr2.ndim)
arr3 = np.zeros((2,3))
print(arr3)
print(arr3.ndim)

[0. 0. 0. 0. 0.]
1
[[0. 0. 0.]
 [0. 0. 0.]]
2


In [12]:
arr4 = np.full((2,3), 10)
print(arr4)

[[10 10 10]
 [10 10 10]]


In [14]:
arr5 = np.arange(2,10)
print(arr5)

[2 3 4 5 6 7 8 9]


In [18]:
arr6 = np.linspace(0,10, 6)
print(arr6)

[ 0.  2.  4.  6.  8. 10.]


In [19]:
idmat = np.eye(4)
print(idmat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
idmat2 = np.identity(3)
print(idmat2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
grades = np.array([49,67,88,69,96])
print(grades.min())
print(grades.max())
print(grades.mean())

49
96
73.8
