In [1]:
import numpy as np
a = np.array([1,2,3])
b= np.array([4,5,6])
np.dot(a,b)

np.int64(32)

In [2]:
a @ b

np.int64(32)

In [3]:
weights = np.array([0.5, 0.2, 0.8])
features = np.array([10, 20, 5])

result = np.dot(weights, features)

print(result)

13.0


In [4]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [5]:
A @ B

array([[19, 22],
       [43, 50]])

In [6]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

In [7]:
## element-wise multiplication
A * B

array([[ 5, 12],
       [21, 32]])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])