In [1]:
## Numpy: indexing, slicing, boolean masking
## 1d indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


In [2]:
## negative indexing
print(arr[-1])

50


In [9]:
## 2d indexing
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[0,1]) ## [row,column]
print(arr[0]) ## entire row
print(arr[:,1]) ## entire column
print(arr[0:2]) ## multiple rows
print(arr[:,0:2]) ## multiple columns

20
[10 20 30]
[20 50 80]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]
 [70 80]]


In [12]:
print(arr[0:2,1:3]) ## submatrix

[[20 30]
 [50 60]]


In [15]:
## slicing
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[2:7])
print(arr[::2])
print(arr[::-1])

[2 3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [16]:
## fancy indexing
arr = np.array([10,20,30,40,50])

print(arr[[0,2,4]])

[10 30 50]


In [19]:
## boolean masking
numbers = np.array([10,20,30,40,50])
mask = numbers > 25
print(mask)
print(numbers[mask])
print(numbers[numbers < 30])

[False False  True  True  True]
[30 40 50]
[10 20]


In [23]:
## in numpy conditions do not use AND , OR use &, |
numbers = np.array([1,5,10,15,20,25])

result = numbers[(numbers > 5) & (numbers < 20)]

print(result)

result = numbers[(numbers < 5) | (numbers > 20)]

print(result)

numbers = np.array([1,2,3,4,5])

result = numbers[~(numbers > 3)]

print(result)

[10 15]
[ 1 25]
[1 2 3]


In [24]:
## filtering a 2d array
data = np.array([
    [1, 20],
    [2, 30],
    [3, 15],
    [4, 40]
])
result = data[data[:,1] > 20]
print(result)

[[ 2 30]
 [ 4 40]]


In [25]:
numbers = np.array([10,20,30,40,50])

indices = np.where(numbers > 25)

print(indices)

(array([2, 3, 4]),)


In [26]:
numbers = np.array([10,20,30,40])

result = np.where(numbers > 25, "High", "Low")

print(result)


['Low' 'Low' 'High' 'High']


In [29]:
## copy vs view
## view edits in the original array
arr = np.array([1,2,3,4,5])

view = arr[1:4]

view[0] = 100

print(arr)

copy_arr = arr[1:4].copy()

copy_arr[0] = 500

print(arr)
print(copy_arr)

[  1 100   3   4   5]
[  1 100   3   4   5]
[500   3   4]
