In [2]:
import numpy as np

rng = np.random.default_rng(42)

# Generate data
data = rng.normal(
    loc=50,
    scale=10,
    size=(100, 3)
)

# Summary
print("Shape:", data.shape)
print("Mean:", np.mean(data, axis=0))
print("Std:", np.std(data, axis=0))

# Normalize
minimum = np.min(data, axis=0)
maximum = np.max(data, axis=0)

normalized = (
    (data - minimum) /
    (maximum - minimum)
)

print(normalized[:5])

Shape: (100, 3)
Mean: [49.70799036 49.86548546 49.19415706]
Std: [8.97305795 9.71728968 9.1415711 ]
[[0.56178208 0.21642527 0.60622734]
 [0.71346981 0.03587284 0.23109326]
 [0.5195864  0.35985662 0.46600606]
 [0.28558675 0.5968091  0.61122407]
 [0.50484108 0.64592676 0.55451753]]


In [3]:
data2 = np.array([
    [20, 3000, 2],
    [25, 4500, 4],
    [30, 6000, 5],
    [35, 7000, 7],
    [40, 9000, 8]
])
print(np.shape(data2)[0]) ## number of rows
print(np.mean(data2,axis=0))
print(np.std(data2,axis=0))
print(np.min(data2,axis=0))

5
[3.0e+01 5.9e+03 5.2e+00]
[   7.07106781 2059.1260282     2.13541565]
[  20 3000    2]


In [4]:
data2[data2[:,1]> 5000]

array([[  30, 6000,    5],
       [  35, 7000,    7],
       [  40, 9000,    8]])

In [5]:
data2[(data2[:,0] >= 30) & (data2[:,2] >= 5)]

array([[  30, 6000,    5],
       [  35, 7000,    7],
       [  40, 9000,    8]])

In [6]:
data3 = np.array([
    [20, 3000, 0],
    [25, 4500, 1],
    [30, 6000, 1],
    [35, 7000, 0]
])

x = data3[:,:2]
y = data3[:,2]
print(x)
print(y)

[[  20 3000]
 [  25 4500]
 [  30 6000]
 [  35 7000]]
[0 1 1 0]


In [7]:
data = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

mean = np.mean(data,axis=0)
std = np.std(data,axis=0)
standardized = (data - mean) / std
print(standardized)

[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


In [8]:
data = np.array([
    10, 12, 11, 13, 12,
    14, 15, 13, 12, 100
])

Q1 = np.percentile(data,25)
Q3 = np.percentile(data,75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 *IQR
upper_bound = Q3 + 1.5 *IQR

outliers = data[
    (data < lower_bound) |
    (data > upper_bound)
]
print(outliers)

[100]


In [9]:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

weights = np.array([2, 3])
bias = 5

prediction = X @ weights + bias
print(prediction)

[13 23 33]


In [10]:
probabilities = np.array([
    [0.1, 0.8, 0.1],
    [0.7, 0.2, 0.1],
    [0.2, 0.3, 0.5],
    [0.05, 0.9, 0.05]
])



In [11]:
data = np.array([
    [10, 20],
    [15, np.nan],
    [20, 30],
    [25, 40]
])

total_nan = sum(np.isnan(data))
print(total_nan)
mean = np.nanmean(data[:,1])
print(mean)
data[:,1] = np.where(
    np.isnan(data[:,1]),mean,data[:,1]
)
print(data)

[0 1]
30.0
[[10. 20.]
 [15. 30.]
 [20. 30.]
 [25. 40.]]
