In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(arr)
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [2]:
reshaped2 = arr.reshape(3,-1)
print(reshaped2)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


In [4]:
print(np.transpose(reshaped))

[[1 4]
 [2 5]
 [3 6]]


In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

parts = np.split(arr, 3)

print(parts)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
data = np.array([
    [25, 30000, 1],
    [30, 40000, 3],
    [35, 50000, 5]
])
age = data[:, 0]
print(age)

[25 30 35]


In [13]:
salary = data[:,1]
experience = data[:,2]