In [1]:
## basic arithmetic
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr + 10)
print(arr ** 2)

[11 12 13 14 15]
[ 1  4  9 16 25]


In [3]:
a = np.array([1,2,3])
b = np.array([5,6,7])
print(a + b)

[ 6  8 10]


In [4]:
## operations and comparisons are element-wise

In [5]:
## functions
arr = np.array([1,4,9,16])
res = np.sqrt(arr)
print(arr)
print(type(arr))
print(res)
print(type(res))

[ 1  4  9 16]
<class 'numpy.ndarray'>
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [6]:
arr = np.array([0,1,2])
print(np.exp(arr))

[1.         2.71828183 7.3890561 ]


In [7]:
arr = np.array([1,np.e,np.e**2])
print(np.log(arr))
print(np.log10(arr))

[0. 1. 2.]
[0.         0.43429448 0.86858896]


In [8]:
arr = np.array([-5,4,3,-2,1])
print(np.abs(arr))

[5 4 3 2 1]


In [9]:
arr = np.array([2.445, 3.556,4.564])
print(np.round(arr,2))

[2.44 3.56 4.56]


In [10]:
arr = np.array([2.445, 3.556,4.564,5.6,6.3,8.1])
print(np.floor(arr))
print(np.ceil(arr))

[2. 3. 4. 5. 6. 8.]
[3. 4. 5. 6. 7. 9.]


In [11]:
## standardization
arr = np.array([10,20,30,40,50])
mean = np.mean(arr)
std = np.std(arr)
z = (arr - mean) / std
print(z)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
