In [1]:
import numpy as np

In [2]:
data = np.array([10,20,30,40,50])
np.sum(data)

np.int64(150)

In [3]:
np.mean(data)

np.float64(30.0)

In [4]:
np.median(data)

np.float64(30.0)

In [6]:
np.var(data)

np.float64(200.0)

In [7]:
np.std(data)

np.float64(14.142135623730951)

In [8]:
## mean of each column
data = np.array([
    [10, 20, 30],
    [20, 40, 60],
    [30, 60, 90]
])
np.mean(data,axis=0)

array([20., 40., 60.])

In [9]:
## mean of each row
np.mean(data,axis=1)

array([20., 40., 60.])

In [10]:
np.argmax(data)

np.int64(8)

In [12]:
flattened = data.flatten()
np.sort(flattened)

array([10, 20, 20, 30, 30, 40, 60, 60, 90])

In [14]:
np.sort(flattened)[::-1]

array([90, 60, 60, 40, 30, 30, 20, 20, 10])

In [15]:
scores = np.array([40, 60, 80, 30])

result = np.where(scores >= 50, "Pass", "Fail")

print(result)

['Fail' 'Pass' 'Pass' 'Fail']


In [16]:
np.random.randint(1, 10)


4

In [17]:
np.random.rand(5)

array([0.81255919, 0.10588909, 0.81010218, 0.88715142, 0.34675218])

In [18]:
np.random.randint(1, 10, size=5)

array([8, 6, 3, 8, 9], dtype=int32)

In [19]:
np.random.randint(
    1,
    100,
    size=(3, 4)
)

array([[93, 95, 34, 18],
       [68, 99, 24,  3],
       [98,  5, 59, 97]], dtype=int32)

In [44]:

data = np.array([10, 20, np.nan, 40])
np.isnan(data)


array([False, False,  True, False])

In [45]:
np.nanmean(data)

np.float64(23.333333333333332)

In [46]:
data = np.array([1, 2, np.inf, 4])

print(np.isinf(data))

[False False  True False]
